# -*- coding: utf-8 -*-
"""Placement_FP-Growth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_14gaVAvYEKNVSF-3A9ghzcjBTbAQaK0
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Placement/Market_Basket_Optimisation.csv',header=None)

df

transactions = []

for i in range(len(df)):
    transaction = []

    for j in range(len(df.columns)):
        item = str(df.iloc[i, j])

        if item != 'nan':
            transaction.append(item)

    transactions.append(transaction)

!pip install mlxtend

from mlxtend.preprocessing import TransactionEncoder

te = TransactionEncoder()

te_array = te.fit(transactions).transform(transactions)

basket = pd.DataFrame(
    te_array,
    columns=te.columns_
)

from mlxtend.frequent_patterns import fpgrowth

frequent_patterns = fpgrowth(
    basket,
    min_support=0.03,
    use_colnames=True
)

print(frequent_patterns)

from mlxtend.frequent_patterns import association_rules

rules = association_rules(
    frequent_patterns,
    metric="confidence",
    min_threshold=0.3
)

print(rules)

