# -*- coding: utf-8 -*-
"""Placement_Apriori.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19CDfxaWQ79RpPAWO3SxSUT6JTIjjLsGs
"""

import numpy as np
import pandas as pd

df = pd.read_csv("/content/drive/MyDrive/Placement/Market_Basket_Optimisation.csv",header=None)

df.isnull().sum()

df

transactions = []
for i in range(0,len(df)):
  transactions.append([str(df.values[i,j])
  for j in range(0,20) if str(df.values[i,j]) != 'NaN'])

!pip install apyori

from apyori import apriori

rules=apriori(transactions=transactions,min_support=0.003,min_confidence=0.2,min_lift=3,min_length=2,max_length=2)

results=list(rules)

results

import pandas as pd

rules_df = pd.DataFrame([
    [
        list(rule[2][0][0]),   # LHS
        list(rule[2][0][1]),   # RHS
        rule[1],               # Support
        rule[2][0][2],         # Confidence
        rule[2][0][3]          # Lift
    ]
    for rule in results
], columns=['LHS', 'RHS', 'Support', 'Confidence', 'Lift'])

rules_df







