# -*- coding: utf-8 -*-
"""Placement_Eclat.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mAEYlFE3cd6wDNFuTEscHS2m_2hnNdsI
"""

import numpy as np
import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/Placement/Market_Basket_Optimisation.csv',header=None)

df

min_support = 2

# Convert to Vertical Format
item_tid = {}

for col in df.columns:

    tidset = set()

    for row in range(len(df)):

        if df.loc[row, col] == 1:
            tidset.add(row)

    item_tid[col] = tidset

# Store results
frequent_itemsets = []

# Step 2: ECLAT Function
def eclat(prefix, items):

    while items:

        item, tidset = items.pop()

        support = len(tidset)

        if support >= min_support:

            frequent_itemsets.append(
                (prefix + [item], support)
            )

            suffix = []

            for other_item, other_tidset in items:

                new_tidset = tidset.intersection(other_tidset)

                if len(new_tidset) >= min_support:
                    suffix.append(
                        (other_item, new_tidset)
                    )

            eclat(prefix + [item], suffix)

items = list(item_tid.items())

eclat([], items)

for itemset, support in frequent_itemsets:
    print(itemset, "Support =", support)